Личный проект: больше деталей (часть 1)
htmlacademy-javascript/1085399-keksobooking-21 pull request #2
Opened 2020-10-01 19:05 UTC by valentin74123

2020-10-03 08:26 UTC, urazaev requested changes

2020-10-03 08:26 UTC, urazaev commented on js/main.js
> +let OFFER_TYPE = [
Тут и далее именовать лучше единообразно, во множественном именно числе в данных моковых константах.

2020-10-03 08:26 UTC, urazaev commented on js/main.js
> +
Можно объединить, данные одинаковые ведь

2020-10-03 08:26 UTC, urazaev commented on js/main.js
> +  pinElement.style.cssText = `left: ` + (apartment.location.x + LOCATION_OFFSET_X) + `px; top: ` + (apartment.location.y + LOCATION_OFFSET_Y) + `px;`;
```
Координаты метки на карте в Кексобукинге — это координаты на которые указывает метка своим острым концом, а не координаты левого верхнего угла блока, обратите на это внимание.
```
Таким образом тебе нужно отнимать половину ширины метки от `x` и целую высоту от `y` вот тут обвел тебе красным размеры чтобы ты ориентировался на метку 
![image](https://user-images.githubusercontent.com/22894816/94986730-7dd21100-057a-11eb-8e2d-937fb3828f8b.png)

2020-10-03 08:26 UTC, urazaev commented on js/main.js
> +let LOCATION_X_MAX = 900;
Что по x что по y довольно странные и некорректные ограничения, посмотри в тексте тз, в тексте задания, цифры должны быть другие. Если не будет понятно, пиши подскажу.

2020-10-03 08:26 UTC, urazaev commented on js/main.js
> +        avatar: `img/avatars/user0` + apartmentNumber + `.png`
`apartmentNumber` используешь вне цикла и по этому на всех пинах аватарка идет одна и та же, по скольку цикл уже пробежал.

2020-10-03 08:26 UTC, urazaev commented on js/main.js
> +        address: location_.x + `, ` + location_.y,
На самом деле проще можно прямо тут рандомно генерить при помощи твоей же `randomInteger` координаты.

2020-10-03 08:26 UTC, urazaev commented on js/main.js
> +        price: `стоимость`,
Число должно быть

2020-10-03 08:26 UTC, urazaev commented on js/main.js
> +        type: OFFER_TYPE[Math.floor(Math.random() * OFFER_TYPE.length)],
Тут и далее можешь просто уже использовать `randomInteger` же которое вернут случайный индекс массива, что и станет твоим текущим случайным значением.

2020-10-03 08:26 UTC, urazaev commented on js/main.js
> +let unique = function (arr) {
Название функции должно по критериям содержать глагол, да и в совокупности по именованию, должно быть понятно что она делает, а тут нет такого понимания.

2020-10-03 08:26 UTC, urazaev commented on js/main.js
> +    let photos = [];
Опять таки имя функции должно иметь глагол и сделать чтото более подходящие по смыслу, например `generatePhotos` по скольку ниже у тебя идет точно такой же ключ `photos`

2020-10-05 13:36 UTC, valentin74123 commented on js/main.js
> +        avatar: `img/avatars/user0` + apartmentNumber + `.png`
В консоли все нормально отображается, но на самом сайте у всех 07 картинка
![image](https://user-images.githubusercontent.com/58230964/95084421-4bb9de00-0737-11eb-9d9d-b721bce86922.png)

может я как-то неправильно их подключил?
![image](https://user-images.githubusercontent.com/58230964/95085053-2083be80-0738-11eb-93ea-d6ee1dd7c9af.png)

2020-10-05 13:42 UTC, valentin74123 commented on js/main.js
> +        address: location_.x + `, ` + location_.y,
скорее всего здесь у меня та же проблема, не подключились координаты адреса
![image](https://user-images.githubusercontent.com/58230964/95086421-ea473e80-0739-11eb-8aee-31f5dcee7e57.png)

![image](https://user-images.githubusercontent.com/58230964/95086665-31353400-073a-11eb-9a07-6abc072207c2.png)

2020-10-05 14:31 UTC, urazaev requested changes

2020-10-05 14:31 UTC, urazaev commented on js/main.js
> +let LOCATION_OFFSET_Y = 70;
https://up.htmlacademy.ru/javascript/21/project/keksobooking#keksobooking-4-4

2020-10-05 14:31 UTC, urazaev commented on js/main.js
> +        price: Number(`1`),
Я когда тебе говорил про число, ждал что ты тут сделаешь тоже рандомную генерацию в диапазоне, с помощью например `randomInteger`

2020-10-05 14:31 UTC, urazaev commented on js/main.js
>    pinElement.getElementsByTagName(`IMG`).alt = apartment.offer.title;
Множественный дом операци лучше делать по ссылке, да и метод `getElementByTagName` давай лучше на привычный `querySelector` заменим.
Например вот так 

```

  var elMapPinImage = pinElement.querySelector(`img`);

  elMapPinImage.src = apartment.author.avatar;
  elMapPinImage.alt = apartment.offer.title;
```

2020-10-07 10:35 UTC, urazaev commented on js/main.js
> +      y: randomInteger(LOCATION_Y + LOCATION_PIN_HEIGHT, LOCATION_Y_MAX - LOCATION_PIN_HEIGHT),
LOCATION_PIN_WIDTH и LOCATION_PIN_HEIGHT лишние в этой формуле , ведь ограничения по координатам мы уже заложили в LOCATION_X, LOCATION_Y, LOCATION_X_MAX, LOCATION_Y_MAX
Этого достаточно.

2020-10-07 10:35 UTC, merged