Личный проект: доверяй, но проверяй (часть 2)
htmlacademy-javascript/1085399-keksobooking-21 pull request #5
Opened 2020-10-21 11:29 UTC by valentin74123

2020-10-22 08:22 UTC, urazaev requested changes
Неплохая структура по заданию, ты проделал большую работу!
Давай кое какие изменения внесем по коду, а так же чисто косметически вот этот сообщение https://yadi.sk/d/hQ49Y54ZILFNWQ давай переместим к инпутам которые отвечают за кол-во гостей и комнат, чтобы `ux` был удобнее.

2020-10-22 08:22 UTC, urazaev commented on js/main.js
> +      };
В консоле если нажать два раза при открытой карточке `esc` выводятся error https://yadi.sk/d/EKEbh9EzWu6qvg
Так происходит из-за не снятого во время обработчика.

2020-10-22 08:22 UTC, urazaev commented on js/main.js
> +      }
Еще проще можно было привязаться к классу например `class="map__card popup"` смотреть, если он есть в разметке, то удалять его (`.remove()`). Вариант кажется проще.

2020-10-22 08:22 UTC, urazaev commented on js/main.js
> +        }
Примерно тут нужно снять обработчик теперь этот, если он отработал.

2020-10-22 15:13 UTC, valentin74123 commented on js/main.js
> +        }
я сделал снятие обработчика, когда я выбираю один раз, то все работает нормально, но когда я например нажал на один пин, потом на другой, и уже потом закрыл, то появляется та же ошибка

2020-10-24 08:30 UTC, urazaev commented on js/main.js
> +        }
Да проблема с обработчиками актуальна, смотри https://yadi.sk/d/GxUx215E6f-AjQ ты каждый раз при клике на пин ставишь обработчик на window для нажатия esc но снимаешь его только если отработала функция `isEscEvent` по этому они суммируются если я тыкаю по разным пинам. Отсюда встает вопрос, с тем чтобы его снять. Либо ставить обработчик при открытии карточки например и при закрытии снимать.

2020-10-24 08:31 UTC, urazaev commented
Все почти готово давай вот тут допилим только https://github.com/htmlacademy-javascript/1085399-keksobooking-21/pull/5#discussion_r511337196

2020-10-26 07:41 UTC, merged